begin;

create schema if not exists timekeeping;

create table if not exists timekeeping.app_state (
    key text primary key,
    json_value jsonb not null,
    updated_at timestamptz not null default now()
);

create table if not exists timekeeping.employees (
    employee_id integer primary key check (employee_id > 0),
    short_name text not null check (length(btrim(short_name)) > 0),
    full_name text not null check (length(btrim(full_name)) > 0),
    schedule_in time not null,
    schedule_out time not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint employees_schedule_order check (schedule_out > schedule_in)
);

create table if not exists timekeeping.employee_audit_log (
    audit_id bigint generated by default as identity primary key,
    employee_id integer,
    action text not null check (action in ('create', 'update', 'delete', 'import')),
    before_json jsonb,
    after_json jsonb,
    changed_at timestamptz not null default now()
);

create index if not exists idx_employee_audit_changed_at
    on timekeeping.employee_audit_log (changed_at desc);

create table if not exists timekeeping.employee_snapshots (
    snapshot_id bigint generated by default as identity primary key,
    reason text not null,
    employees_json jsonb not null,
    created_at timestamptz not null default now()
);

revoke all on schema timekeeping from anon, authenticated;
revoke all on all tables in schema timekeeping from anon, authenticated;
revoke all on all sequences in schema timekeeping from anon, authenticated;

alter table timekeeping.app_state enable row level security;
alter table timekeeping.employees enable row level security;
alter table timekeeping.employee_audit_log enable row level security;
alter table timekeeping.employee_snapshots enable row level security;

commit;
